O_TARGET:= gui.o
obj-y=bmp/libbmp.o control/libcontrol.o lguicore/liblguicore.o gdi/libgdi.o\
	hdc/libhdc.o ial/libial.o ime/libime.o src/src.o
subdir-y=src bmp control lguicore gdi hdc ial ime 
include $(TOPDIR)/rule.mk
