/*
 * Automatically generated by make menuconfig: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Pal Configuration
 */
#undef  CFG_ARM_S3C2410
#undef  CFG_ARM_S3C2440
#undef  CFG_ARM_S3C44B0
#undef  CFG_ARM_LPC2131
#undef  CFG_ARM_LPC2200
#define CFG_ARM_PB11MPCORE 1
#undef  CFG_ARM_STM3210
#undef  CFG_X86_EMU_SINGLE
#undef  CFG_X86_EMU_CMP
#define CFG_CMP 1
#define CFG_MAX_CPU (3)
#undef  CFG_NAND_BOOT

/*
 * kernel configuration
 */
#define CFG_MEM_BUDDY 1
#undef  CFG_MEM_SLATE
#define CFG_MEM2 1
#define CFG_MEM2_SIZE (256)
#undef  CFG_THRD_PERIOD
#undef  CFG_THRD_SLICE
#undef  CFG_THRD_POSIX
#define CFG_HARD_RT_PRIO_NUM (1)
#define CFG_MAX_THREAD (10)
#define CFG_MIN_STACK_SIZE (256)
#undef  CFG_PM
#undef  CFG_EVT_MBOX
#undef  CFG_EVT_SEM
#undef  CFG_MSG
#define CFG_TICKS_ENABLE 1
#define CFG_SOFT_DELAY 1
#define CFG_TICKS_PER_SEC (100)
#undef  CFG_HOOK

/*
 * Driver configuration
 */
#define CFG_DRIVER 1
#define CFG_DRV_CONSOLE 1

/*
 * Bsp configuration
 */

/*
 * Plugin configuration
 */
#undef  CFG_PLUGIN_GUI
#undef  CFG_PLUGIN_NET
#undef  CFG_PLUGIN_FS

/*
 * lib configuration
 */
#define CFG_LIB_EXT 1

/*
 * Test configuration
 */
#undef  CFG_TEST

/*
 * User configuration
 */
#define CFG_SHELL 1
#define CFG_UART_SHELL 1
#undef  CFG_TELNET_SHELL
#undef  CFG_WEB_SERVER

/*
 * System hacking
 */
#define CFG_BAUD_RATE (38400)
#undef  CFG_OUT_SEMI
#undef  CFG_DEBUG
#undef  CFG_STAT
